# Generated by Django 4.2.2 on 2023-06-22 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rewards", "0001_initial"),
        ("goals", "0003_friend_alter_usergoal_friend"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergoal",
            name="rewards",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_goals",
                to="rewards.reward",
            ),
        ),
    ]
