# Generated by Django 4.2.2 on 2023-06-22 22:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0004_usergoal_rewards"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usergoal",
            old_name="rewards",
            new_name="reward",
        ),
    ]
