# Generated by Django 4.2.2 on 2023-06-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0005_rename_rewards_usergoal_reward"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usergoal",
            name="friend",
            field=models.CharField(max_length=255),
        ),
    ]
