# Generated by Django 4.2.2 on 2023-06-23 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0006_alter_usergoal_friend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usergoal",
            name="friend",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_goals",
                to="goals.friend",
            ),
        ),
    ]
